name: Build and Test
on:  
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Node
        uses: actions/setup-node@v4
        with:
          node-version: "22.x"

      - name: Install pnpm
        uses: pnpm/action-setup@v4  
        with:
          version: '9.x'    
      
      - name: Install dependencies
        run: pnpm install

      - name: Run Linter
        run: pnpm run lint

      - name: Run formatter
        run: pnpm run format

      - name: Run build
        run: pnpm build

      - name: Run cypress tests
        uses: cypress-io/github-action@v6
        with:        
          start: pnpm run dev
          wait-on: 'http://localhost:3000'
          command: "pnpm cypress run --browser=chrome --record"
          record: true
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          GITHUB_TOKEN: ${{ secrets.ACT_GITHUB_TOKEN }} 

      - name: Upload cypress screenshots
        uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: cypress-screenshots
          path: cypress/screenshots

      - name: Upload cypress videos
        uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: cypress-videos
          path: cypress/videos