name: Build and Test
on:  
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Node
        uses: actions/setup-node@v4
        with:
          node-version: "22.x"

      - name: Install pnpm
        uses: pnpm/action-setup@v4  
        with:
          version: '9.x'    
      
      - name: Install dependencies
        run: pnpm install

      - name: Run Linter
        run: pnpm run lint

      # - name: Run formatter
      #   run: pnpm format

      - name: Run build
        run: pnpm build